import StickyNav from "components/navigation/StickyNav";
import AuthSession from "components/providers/session-provider";
import CommonLayout from "layouts/CommonLayout";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/index.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Pretendard = localFont({
  src: [
    {
      path: "./fonts/Pretendard-Regular.woff2",
      weight: "400",
    },
    {
      path: "./fonts/Pretendard-Medium.woff2",
      weight: "500",
    },
    {
      path: "./fonts/Pretendard-SemiBold.woff2",
      weight: "600",
    },
    {
      path: "./fonts/Pretendard-Bold.woff2",
      weight: "700",
    },
    {
      path: "./fonts/Pretendard-ExtraBold.woff2",
      weight: "800",
    },
  ],
});

const SpecialFont = localFont({
  src: "./fonts/Ownglyph-PDH.ttf",
  variable: "--font-Ownglyph-PDH",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className={`${Pretendard.className} ${SpecialFont.variable}`}>
        <CommonLayout header={<StickyNav />}>
          <AuthSession>{children}</AuthSession>
        </CommonLayout>
      </body>
    </html>
  );
}
